name: Build & Push OCI Image to Registry

on:
  workflow_call:
    inputs:
      rootdir:
        required: true
        type: string
      workdir:
        required: true
        type: string
      image-name:
        required: true
        type: string
    secrets:
      github-username:
        required: true
      github-token:
        required: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    continue-on-error: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - name: Set up QEMU for Docker Buildx
        uses: docker/setup-qemu-action@2b82ce82d56a2a04d2637cd93a637ae1b359c0a7 # v2.2.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@6a58db7e0d21ca03e6c44877909e80e45217eed2 # v2.6.0

      - name: Set up Node.js for extracting recipe from Dockerfile
        uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c # v3.6.0
        with:
          node-version: 18
          check-latest: true

      - name: Install meow dependencies for extracting recipe from Dockerfile
        run: npm i --no-save meow@11.x

      - name: Set WORKDIR and ROOTDIR
        run: |
          echo "WORKDIR=${{ inputs.workdir }}" >> $GITHUB_ENV
          echo "ROOTDIR=${{ inputs.rootdir }}" >> $GITHUB_ENV

      - name: Extract recipe from Dockerfile
        id: recipe
        run: |
          TAGS=`node ${{ github.workspace }}/extractImage.mjs $WORKDIR/Dockerfile tags`
          PLATFORMS=`node ${{ github.workspace }}/extractImage.mjs $WORKDIR/Dockerfile platforms`
          VARIANT=`node ${{ github.workspace }}/extractImage.mjs $WORKDIR/Dockerfile variant`
          echo TAGS: $TAGS
          echo PLATFORMS: $PLATFORMS
          echo VARIANT: $VARIANT
          echo "::set-output name=tags::${TAGS//$', '/'%0A'}"
          echo "::set-output name=platforms::${PLATFORMS//$', '/'%0A'}"
          echo "::set-output name=variant::$VARIANT"

      - name: Generate Docker image metadata
        uses: docker/metadata-action@2c0bd771b40637d97bf205cbccdd294a32112176 # v4.5.0
        id: meta
        with:
          images: |
            ghcr.io/Clytage/${{ inputs.image-name }}
          tags: |
            ${{ steps.recipe.outputs.tags }}

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v2.2.0
        with:
          registry: ghcr.io
          username: ${{ secrets.github-username }}
          password: ${{ secrets.github-token }}

      - name: Build and push the Docker image from the specified Dockerfile
        id: docker_build
        uses: docker/build-push-action@44ea916f6c540f9302d50c2b1e5a8dc071f15cdf # v4.1.0
        with:
          context: ${{ env.ROOTDIR }}
          file: ${{ env.WORKDIR }}/Dockerfile
          platforms: |
            ${{ steps.recipe.outputs.platforms }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
