name: Build & Push OCI Image to Registry

on:
  workflow_call:
    inputs:
      rootdir:
        required: true
        type: string
      workdir:
        required: true
        type: string
      image-name:
        required: true
        type: string

permissions:
  contents: read
  packages: write

jobs:
  build:
    continue-on-error: true

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up QEMU for Docker Buildx
        uses: docker/setup-qemu-action@68827325e0b33c7199eb31dd4e31fbe9023e06e3 # v3.0.0

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@d70bba72b1f3fd22344832f00baa16ece964efeb # v3.3.0

      - name: Set up Node.js for extracting recipe from Dockerfile
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: 20
          check-latest: true

      - name: Install meow dependencies for extracting recipe from Dockerfile
        run: npm i --no-save meow@13.1.x

      - name: Set WORKDIR and ROOTDIR
        run: |
          echo "WORKDIR=${{ inputs.workdir }}" >> $GITHUB_ENV
          echo "ROOTDIR=${{ inputs.rootdir }}" >> $GITHUB_ENV

      - name: Extract recipe from Dockerfile
        id: recipe
        run: |
          TAGS=`node ${{ github.workspace }}/extractImage.mjs $WORKDIR/Dockerfile tags`
          PLATFORMS=`node ${{ github.workspace }}/extractImage.mjs $WORKDIR/Dockerfile platforms`
          VARIANT=`node ${{ github.workspace }}/extractImage.mjs $WORKDIR/Dockerfile variant`
          echo TAGS: $TAGS
          echo PLATFORMS: $PLATFORMS
          echo VARIANT: $VARIANT
          echo "::set-output name=tags::${TAGS//$', '/'%0A'}"
          echo "::set-output name=platforms::${PLATFORMS//$', '/'%0A'}"
          echo "::set-output name=variant::$VARIANT"

      - name: Generate Docker image metadata
        uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # v5.5.1
        id: meta
        with:
          images: |
            ghcr.io/Stegripe/${{ inputs.image-name }}
          tags: |
            ${{ steps.recipe.outputs.tags }}

      - name: Login to GitHub Container Registry
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@e92390c5fb421da1463c202d546fed0ec5c39f20 # v3.1.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image from the specified Dockerfile
        id: docker_build
        uses: docker/build-push-action@2cdde995de11925a030ce8070c3d77a52ffcf1c0 # v5.3.0
        with:
          context: ${{ env.ROOTDIR }}
          file: ${{ env.WORKDIR }}/Dockerfile
          platforms: |
            ${{ steps.recipe.outputs.platforms }}
          push: ${{ github.event_name == 'push' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
