name: Build & Push Golang to OCI Image Registry

on:
  push:
    branches:
      - main
    paths:
      - "golang/**/**/Dockerfile"
      - "golang/entrypoint.sh"
  pull_request:
    branches:
      - main
    paths:
      - "golang/**/**/Dockerfile"
      - "golang/entrypoint.sh"

jobs:
  golang-alpine:
    name: Golang ${{ matrix.version }} Alpine

    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.14
          - 1.15
          - 1.16
          - 1.17
          - 1.18
          - 1.19
          - "1.20"
          - 1.21

    uses: ./.github/workflows/build.yml
    with:
      rootdir: golang
      workdir: golang/${{ matrix.version }}/alpine
      image-name: golang
    secrets: inherit

  golang-debian:
    name: Golang ${{ matrix.version }} Debian
    needs: golang-alpine

    strategy:
      fail-fast: false
      matrix:
        version:
          - 1.14
          - 1.15
          - 1.16
          - 1.17
          - 1.18
          - 1.19
          - "1.20"
          - 1.21

    uses: ./.github/workflows/build.yml
    with:
      rootdir: golang
      workdir: golang/${{ matrix.version }}/debian
      image-name: golang
    secrets: inherit
