name: Build and Push MongoDB to OCI Image Registry

on:
  push:
    branches:
      - main
    paths:
      - "mongo/**/Dockerfile"
      - "mongo/entrypoint.sh"
  pull_request:
    branches:
      - main
    paths:
      - "mongo/**/Dockerfile"
      - "mongo/entrypoint.sh"

jobs:
  push-mongo:
    name: MongoDB ${{ matrix.version }}

    strategy:
      fail-fast: false
      matrix:
        version:
          - 4
          - 5
          - 6

    uses: ./.github/workflows/build.yml
    with:
      rootdir: mongo
      workdir: mongo/${{ matrix.version }}
      image-name: mongo
    secrets: inherit
