name: Build & Push Node.js to OCI Image Registry

on:
  push:
    branches:
      - main
    paths:
      - "node/**/**/Dockerfile"
  pull_request:
    branches:
      - main
    paths:
      - "node/**/**/Dockerfile"

jobs:
  node-16-alpine:
    name: Node.js 16 Alpine
    uses: ./.github/workflows/build.yml
    with:
      rootdir: node
      workdir: node/16/alpine
      image-name: node
    secrets:
      github-username: ${{ github.repository_owner }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

  node-18-alpine:
    name: Node.js 18 Alpine
    uses: ./.github/workflows/build.yml
    with:
      rootdir: node
      workdir: node/18/alpine
      image-name: node
    secrets:
      github-username: ${{ github.repository_owner }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

  node-16:
    name: Node.js 16 Debian
    uses: ./.github/workflows/build.yml
    with:
      rootdir: node
      workdir: node/16/debian
      image-name: node
    secrets:
      github-username: ${{ github.repository_owner }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

  node-18:
    name: Node.js 18 Debian
    uses: ./.github/workflows/build.yml
    with:
      rootdir: node
      workdir: node/18/debian
      image-name: node
    secrets:
      github-username: ${{ github.repository_owner }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
