name: Build & Push Ubuntu to OCI Image Registry

on:
  push:
    branches:
      - main
    paths:
      - "ubuntu/Dockerfile"
  pull_request:
    branches:
      - main
    paths:
      - "ubuntu/Dockerfile"

jobs:
  push-ubuntu:
    name: Ubuntu

    uses: ./.github/workflows/build.yml
    with:
      rootdir: ubuntu
      workdir: ubuntu
      image-name: ubuntu
    secrets:
      github-username: ${{ github.repository_owner }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

